/**
 * gemini.js — Gemini platform adapter for ThreadMap
 */

window.ThreadMapPlatforms = window.ThreadMapPlatforms || {};

window.ThreadMapPlatforms.gemini = {
    name: 'Gemini',
    capabilities: {},

    getRootContainer() {
        // Gemini has custom app layout tags
        return document.querySelector('chat-window') || document.body;
    },

    getUserMessages() {
        return this._runStrategies([document.body]);
    },

    processAddedNodes(nodes) {
        const candidateElements = Array.from(nodes).filter(n => n.nodeType === Node.ELEMENT_NODE || n.nodeType === Node.TEXT_NODE);
        const rawMessages = this._runStrategies(candidateElements);

        return rawMessages
            .map(el => window.ThreadMapMessageNormalizer.normalize(el, this, "user"))
            .filter(Boolean);
    },

    _runStrategies(candidateElements) {
        let messages = [];

        // 1. Check specific Gemini selectors first (most reliable)
        const geminiSelectors = '.query-text, user-query, [data-user-query], .user-query-content';

        for (const node of candidateElements) {
            const el = node.nodeType === Node.TEXT_NODE ? node.parentElement : node;
            if (!el || el.nodeType !== Node.ELEMENT_NODE) continue;

            if (el.matches && el.matches(geminiSelectors)) {
                messages.push(el);
            } else if (el.closest(geminiSelectors)) {
                messages.push(el.closest(geminiSelectors));
            }

            if (el.querySelectorAll) {
                el.querySelectorAll(geminiSelectors).forEach(m => messages.push(m));
            }
        }

        // 2. Try role attributes if enabled
        if (this.capabilities.roleAttributes) {
            const roleMatches = window.ThreadMapRoleStrategy.detect(candidateElements);
            messages.push(...roleMatches);
        }

        messages = Array.from(new Set(messages));

        // 3. Fallback to Semantic Strategy ONLY if specific selectors fail or for new node processing
        // Avoid running on document.body to prevent grabbing top-level header/nav text
        if (messages.length === 0 && this.capabilities.semanticPattern) {
            const safeCandidates = candidateElements.filter(n =>
                n !== document.body &&
                n !== document.documentElement &&
                n.tagName !== 'HEADER' &&
                n.tagName !== 'NAV'
            );

            if (safeCandidates.length > 0) {
                const semanticMatches = window.ThreadMapSemanticStrategy.detect(safeCandidates, this.getMessageText);
                messages.push(...semanticMatches);
            }
        }

        return Array.from(new Set(messages));
    },

    getMessageText(el) {
        return extractFirstLine(el);
    },

    getMessageId(el) {
        const idAttrs = ['data-message-id', 'data-query-id', 'data-turn-id'];

        let current = el;
        let depth = 0;
        while (current && depth < 10) {
            for (const attr of idAttrs) {
                if (current.getAttribute && current.getAttribute(attr)) {
                    return current.getAttribute(attr);
                }
            }
            // Check for specific Gemini class patterns
            if (current.classList && current.classList.contains('conversation-turn')) {
                // If we hit the outer turn without a data-turn-id, hash the first user-query child we can find
                const innerQuery = current.querySelector('user-query');
                // Ensure we don't grab generic autogenerated lit IDs like id="c23"
                if (innerQuery && innerQuery.id && innerQuery.id.startsWith('query-')) return 'gemini-' + innerQuery.id;
            }

            // Text nodes don't have getAttribute, so parentElement is safer
            current = current.parentElement;
            depth++;
        }
        return null;
    },

    getScrollTarget(el) {
        let current = el;
        let candidate = el;
        let depth = 0;
        while (current && depth < 15) {
            const tagName = current.tagName?.toLowerCase() || '';
            if (
                tagName === 'message-content' ||
                tagName === 'user-query' ||
                current.classList?.contains('conversation-turn') ||
                current.classList?.contains('query-container')
            ) {
                candidate = current;
                break;
            }
            current = current.parentElement;
            depth++;
        }
        return candidate;
    },

    getChatId() {
        let match = window.location.pathname.match(/\/app\/([a-zA-Z0-9_-]+)/);
        if (match) return match[1];
        match = window.location.pathname.match(/\/chat\/([a-zA-Z0-9_-]+)/);
        if (match) return match[1];
        const hash = window.location.hash;
        if (hash && hash.length > 1) return 'gemini-' + simpleHash(hash);

        if (window.location.pathname === '/' || window.location.pathname === '/app') {
            return 'gemini-main';
        }
        return 'gemini-' + simpleHash(window.location.pathname);
    },

    getEmptyStateText() {
        return 'Start asking Gemini something.';
    }
};

if (typeof module !== "undefined" && module.exports) { module.exports = { GeminiAdapter: window.ThreadMapPlatforms.gemini }; }
